### PR TITLE
Hotfix/Allow colour styling

### PR DESCRIPTION
**Pull request by OvidiuToma**
Adds the functionality requested here: https://github.com/gmemstr/notdonemywebsite/issues/3

screen recording 2018-10-10 at 06 12 pm

**Changes:**
- Added a new template to display the color functionality. 
- Adds the color functionality. 

**How it works:**
- The js will search in the iframe for 2 classes: "primary_color" and "secondary_color". The divs that will have those classes will have the background color as defined in the "primary" and "secondary" color inputs. 

**Steps to add coloring functionality to other templates:**
- I tried to include this functionality without introducing major steps. That being said, the steps are:
  -  Add "primary_color" and "secondary_color" classes to the divs in the templates. As many as you want. 
  - ~~Modify the button in the in the index.html with the default values for the color inputs. like: `getTemplateHtml('color_test', '#f5f5dd', '#fec1cb')`. To be noted that the extra 2 color parameters are optional, ex: `getTemplateHtml('material')` still works but the default colors will be white.~~ 
This step has been changed after merging the master. However this still applies under the hood. 
Now`templates.json` should contain the "primary_color" and "secondary_color" keys, like:
`{
    "id": "color_test",
    "name": "Color Test",
    "author": "ovidThomas",
    "primary_color":  "#f5f5dd", 
    "secondary_color": "#fec1cb"
  }`

### CODE REVIEW

**Comment by OvidiuToma** [comment]
**Update:**
After merging master, the default colors process for a template has been changed. Now `templates.json` should contain the "primary_color" and "secondary_color" keys, like:

`{
    "id": "color_test",
    "name": "Color Test",
    "author": "ovidThomas",
    "primary_color":  "#f5f5dd", 
    "secondary_color": "#fec1cb"
  }`

**Comment by macno** [comment]
What about loading dynamically the color fields from templates.json?
```
{
  "id": "color_test", 
  "name": "Color Test", 
  "author": "ovidThomas",  
  "colors": [{
      "id": "primary_color",
      "name": "Main bg",
      "default": "#f5f5dd"
     }, {
        {
      "id": "secondary_color",
      "name": "Block bg",
      "default": "#fec1cb"
     }
   ]
}
```

In this way we're not bonded to 2 colors, authors can add how many they need ( 0 or n)

**Comment by gmemstr** [comment]
Will need to be rerolled, I think we should look into the loading of colours from the json file as macno mentioned

**Comment by OvidiuToma** [comment]
@macno , @gmemstr, good point. Will update.

**Comment by OvidiuToma** [comment]
@gmemstr Fixed.
Items:
- Default colors need to be defined in the `templates.json`, as metined by @macno above. 
- Instead of having one color input for a div, now you can select an element and assign it's color. (In this case there are only 2 colors, there can be n)

screen recording 2018-10-15 at 01 27 pm

**Comment by macno** [comment]
Hi @OvidiuToma nice work! 
Anyway I looked at your implementation and I'd like to point out that colours could be used for everything (background-color, border's color, text color..etc), so I suppose we have to think to a different approach.. IMHO being able to change only the background-color is too limiting

**Comment by gmemstr** [comment]
I'll review this later today - it looks like a good first implementation and while I agree with @macno that we should look at increasing the colour options, I also think we might need to improve the ui/ux for this in general.

**Comment by OvidiuToma** [comment]
@macno Well, in my opinion, any styling can be implemented using this approach, with some minor tweaks. 
Basically, in the `templates.json`, instead of `"default": "#f5f5dd"`, we can do `"background-color": "#f5f5dd"`, and the javascript from the app.js will add those style properties to the div with the id specified in the "id" section. 
Also, in the front-end, we can add another select, which will contain options representing the css properties(maybe not the best looking implementation but it's functional). 

The json could be something like this:
```
"colors": [{
           "id": "primary_color",
           "name": "Main bg",
           "css" : {
               "background-color": "#f5f5dd",
               "border-color": "#000000",
               "color": "#000000"
            }
      } ,
      {
           "id": "secondary_color",
           "name": "Block bg",
           "css" : 
            {
               "background-color": "#f5f5dd"
            }
     }
   ]
```

**Comment by gmemstr** [comment]
Here's what I'll do - I'll merge this request tonight and we can spin the feature of styling everything off into it's own issue

**Pull request merged**
